# Generated by Django 2.2 on 2020-10-21 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201021_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='username1',
        ),
    ]
