# Generated by Django 2.2 on 2020-10-21 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201021_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password1',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username1',
            new_name='username',
        ),
    ]
